### ISSUE TITLE
[client] authenticate method never resolves.

### ISSUE THREAD

**Issue by Dazzuh** [goto-bus-stop/plug-auth#27]
using the following code with what is essentially the example server app yields no results 
```js
authenticate({
    transport: httpTransport({ url: 'https://my-url/auth/login' })
}).then((result) => {
    console.log(result);
    if (!result || !result.token) console.log('no result or token');
}).catch(console.error);
```

This only seems to be an issue with version 1.1.1, using 1.1.0 works as intended. I wasn't able to find the source of the issue, sorry :(

**Comment by goto-bus-stop** [comment]
Looks like a bug in the await→Promises transform :/  Thanks for the report! Fixed in v1.1.2.
